import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        background: "#0D0D0D",
        card: "#171717",
        border: "#2B2B2B",
        accent: "#6366F1",
        success: "#22C55E",
        danger: "#EF4444",
        primary: "#c0c1ff",
        "on-primary": "#1000a9",
        "primary-container": "#8083ff",
        "on-primary-container": "#0d0096",
        surface: "#13131b",
        "surface-dim": "#13131b",
        "surface-bright": "#393841",
        "surface-container-lowest": "#0d0d15",
        "surface-container-low": "#1b1b23",
        "surface-container": "#1f1f27",
        "surface-container-high": "#292932",
        "surface-container-highest": "#34343d",
        "on-surface": "#e4e1ed",
        "on-surface-variant": "#c7c4d7",
        "surface-variant": "#34343d",
        "on-background": "#e4e1ed",
        outline: "#908fa0",
        "outline-variant": "#464554",
        error: "#ffb4ab",
        "error-container": "#93000a",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
        tertiary: "#ffb783",
        "on-tertiary": "#4f2500",
        "tertiary-container": "#d97721",
        "on-tertiary-container": "#452000",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      fontFamily: {
        sans: ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        mono: ["Geist Mono", "ui-monospace", "monospace"],
        inter: ["Inter", "sans-serif"],
        geist: ["Geist", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "500" }],
        "metric-xl": ["48px", { lineHeight: "1", letterSpacing: "-0.04em", fontWeight: "700" }],
      },
      spacing: {
        gutter: "20px",
        "margin-desktop": "32px",
        sm: "12px",
        base: "8px",
        xl: "64px",
        lg: "40px",
        md: "24px",
        xs: "4px",
        "margin-mobile": "16px",
      },
      keyframes: {
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
        blink: {
          "50%": { opacity: "0" },
        },
        "progress-stripes": {
          from: { backgroundPosition: "1rem 0" },
          to: { backgroundPosition: "0 0" },
        },
      },
      animation: {
        blink: "blink 1s step-start infinite",
        "progress-stripes": "progress-stripes 1s linear infinite",
      },
    },
  },
  plugins: [],
};

export default config;
